on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run Unit Tests
        run: go test -coverprofile coverage.txt -race ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: swedishborgie/go-tandoor
          flags: unit
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.13.2
